/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as LodgesRouteImport } from './routes/lodges'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsTadobaIndexRouteImport } from './routes/destinations/tadoba/index'
import { Route as DestinationsRanthamboreIndexRouteImport } from './routes/destinations/ranthambore/index'
import { Route as DestinationsKazirangaIndexRouteImport } from './routes/destinations/kaziranga/index'
import { Route as DestinationsKanhaIndexRouteImport } from './routes/destinations/kanha/index'
import { Route as DestinationsCorbettIndexRouteImport } from './routes/destinations/corbett/index'
import { Route as DestinationsBandhavgarhIndexRouteImport } from './routes/destinations/bandhavgarh/index'
import { Route as DestinationsRanthamboreLodgesIndexRouteImport } from './routes/destinations/ranthambore/lodges/index'
import { Route as DestinationsRanthamboreLodgesJunaMahalRouteImport } from './routes/destinations/ranthambore/lodges/juna-mahal'

const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgesRoute = LodgesRouteImport.update({
  id: '/lodges',
  path: '/lodges',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsTadobaIndexRoute = DestinationsTadobaIndexRouteImport.update({
  id: '/destinations/tadoba/',
  path: '/destinations/tadoba/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRanthamboreIndexRoute =
  DestinationsRanthamboreIndexRouteImport.update({
    id: '/destinations/ranthambore/',
    path: '/destinations/ranthambore/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsKazirangaIndexRoute =
  DestinationsKazirangaIndexRouteImport.update({
    id: '/destinations/kaziranga/',
    path: '/destinations/kaziranga/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsKanhaIndexRoute = DestinationsKanhaIndexRouteImport.update({
  id: '/destinations/kanha/',
  path: '/destinations/kanha/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCorbettIndexRoute =
  DestinationsCorbettIndexRouteImport.update({
    id: '/destinations/corbett/',
    path: '/destinations/corbett/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsBandhavgarhIndexRoute =
  DestinationsBandhavgarhIndexRouteImport.update({
    id: '/destinations/bandhavgarh/',
    path: '/destinations/bandhavgarh/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsRanthamboreLodgesIndexRoute =
  DestinationsRanthamboreLodgesIndexRouteImport.update({
    id: '/destinations/ranthambore/lodges/',
    path: '/destinations/ranthambore/lodges/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsRanthamboreLodgesJunaMahalRoute =
  DestinationsRanthamboreLodgesJunaMahalRouteImport.update({
    id: '/destinations/ranthambore/lodges/juna-mahal',
    path: '/destinations/ranthambore/lodges/juna-mahal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/bandhavgarh/': typeof DestinationsBandhavgarhIndexRoute
  '/destinations/corbett/': typeof DestinationsCorbettIndexRoute
  '/destinations/kanha/': typeof DestinationsKanhaIndexRoute
  '/destinations/kaziranga/': typeof DestinationsKazirangaIndexRoute
  '/destinations/ranthambore/': typeof DestinationsRanthamboreIndexRoute
  '/destinations/tadoba/': typeof DestinationsTadobaIndexRoute
  '/destinations/ranthambore/lodges/juna-mahal': typeof DestinationsRanthamboreLodgesJunaMahalRoute
  '/destinations/ranthambore/lodges/': typeof DestinationsRanthamboreLodgesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/bandhavgarh': typeof DestinationsBandhavgarhIndexRoute
  '/destinations/corbett': typeof DestinationsCorbettIndexRoute
  '/destinations/kanha': typeof DestinationsKanhaIndexRoute
  '/destinations/kaziranga': typeof DestinationsKazirangaIndexRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreIndexRoute
  '/destinations/tadoba': typeof DestinationsTadobaIndexRoute
  '/destinations/ranthambore/lodges/juna-mahal': typeof DestinationsRanthamboreLodgesJunaMahalRoute
  '/destinations/ranthambore/lodges': typeof DestinationsRanthamboreLodgesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/bandhavgarh/': typeof DestinationsBandhavgarhIndexRoute
  '/destinations/corbett/': typeof DestinationsCorbettIndexRoute
  '/destinations/kanha/': typeof DestinationsKanhaIndexRoute
  '/destinations/kaziranga/': typeof DestinationsKazirangaIndexRoute
  '/destinations/ranthambore/': typeof DestinationsRanthamboreIndexRoute
  '/destinations/tadoba/': typeof DestinationsTadobaIndexRoute
  '/destinations/ranthambore/lodges/juna-mahal': typeof DestinationsRanthamboreLodgesJunaMahalRoute
  '/destinations/ranthambore/lodges/': typeof DestinationsRanthamboreLodgesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations/'
    | '/destinations/bandhavgarh/'
    | '/destinations/corbett/'
    | '/destinations/kanha/'
    | '/destinations/kaziranga/'
    | '/destinations/ranthambore/'
    | '/destinations/tadoba/'
    | '/destinations/ranthambore/lodges/juna-mahal'
    | '/destinations/ranthambore/lodges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations'
    | '/destinations/bandhavgarh'
    | '/destinations/corbett'
    | '/destinations/kanha'
    | '/destinations/kaziranga'
    | '/destinations/ranthambore'
    | '/destinations/tadoba'
    | '/destinations/ranthambore/lodges/juna-mahal'
    | '/destinations/ranthambore/lodges'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations/'
    | '/destinations/bandhavgarh/'
    | '/destinations/corbett/'
    | '/destinations/kanha/'
    | '/destinations/kaziranga/'
    | '/destinations/ranthambore/'
    | '/destinations/tadoba/'
    | '/destinations/ranthambore/lodges/juna-mahal'
    | '/destinations/ranthambore/lodges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConservationRoute: typeof ConservationRoute
  ItinerariesRoute: typeof ItinerariesRoute
  LodgesRoute: typeof LodgesRoute
  PhotographyRoute: typeof PhotographyRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  DestinationsBandhavgarhIndexRoute: typeof DestinationsBandhavgarhIndexRoute
  DestinationsCorbettIndexRoute: typeof DestinationsCorbettIndexRoute
  DestinationsKanhaIndexRoute: typeof DestinationsKanhaIndexRoute
  DestinationsKazirangaIndexRoute: typeof DestinationsKazirangaIndexRoute
  DestinationsRanthamboreIndexRoute: typeof DestinationsRanthamboreIndexRoute
  DestinationsTadobaIndexRoute: typeof DestinationsTadobaIndexRoute
  DestinationsRanthamboreLodgesJunaMahalRoute: typeof DestinationsRanthamboreLodgesJunaMahalRoute
  DestinationsRanthamboreLodgesIndexRoute: typeof DestinationsRanthamboreLodgesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodges': {
      id: '/lodges'
      path: '/lodges'
      fullPath: '/lodges'
      preLoaderRoute: typeof LodgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/tadoba/': {
      id: '/destinations/tadoba/'
      path: '/destinations/tadoba'
      fullPath: '/destinations/tadoba/'
      preLoaderRoute: typeof DestinationsTadobaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/ranthambore/': {
      id: '/destinations/ranthambore/'
      path: '/destinations/ranthambore'
      fullPath: '/destinations/ranthambore/'
      preLoaderRoute: typeof DestinationsRanthamboreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/kaziranga/': {
      id: '/destinations/kaziranga/'
      path: '/destinations/kaziranga'
      fullPath: '/destinations/kaziranga/'
      preLoaderRoute: typeof DestinationsKazirangaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/kanha/': {
      id: '/destinations/kanha/'
      path: '/destinations/kanha'
      fullPath: '/destinations/kanha/'
      preLoaderRoute: typeof DestinationsKanhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/corbett/': {
      id: '/destinations/corbett/'
      path: '/destinations/corbett'
      fullPath: '/destinations/corbett/'
      preLoaderRoute: typeof DestinationsCorbettIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/bandhavgarh/': {
      id: '/destinations/bandhavgarh/'
      path: '/destinations/bandhavgarh'
      fullPath: '/destinations/bandhavgarh/'
      preLoaderRoute: typeof DestinationsBandhavgarhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/ranthambore/lodges/': {
      id: '/destinations/ranthambore/lodges/'
      path: '/destinations/ranthambore/lodges'
      fullPath: '/destinations/ranthambore/lodges/'
      preLoaderRoute: typeof DestinationsRanthamboreLodgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/ranthambore/lodges/juna-mahal': {
      id: '/destinations/ranthambore/lodges/juna-mahal'
      path: '/destinations/ranthambore/lodges/juna-mahal'
      fullPath: '/destinations/ranthambore/lodges/juna-mahal'
      preLoaderRoute: typeof DestinationsRanthamboreLodgesJunaMahalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConservationRoute: ConservationRoute,
  ItinerariesRoute: ItinerariesRoute,
  LodgesRoute: LodgesRoute,
  PhotographyRoute: PhotographyRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  DestinationsBandhavgarhIndexRoute: DestinationsBandhavgarhIndexRoute,
  DestinationsCorbettIndexRoute: DestinationsCorbettIndexRoute,
  DestinationsKanhaIndexRoute: DestinationsKanhaIndexRoute,
  DestinationsKazirangaIndexRoute: DestinationsKazirangaIndexRoute,
  DestinationsRanthamboreIndexRoute: DestinationsRanthamboreIndexRoute,
  DestinationsTadobaIndexRoute: DestinationsTadobaIndexRoute,
  DestinationsRanthamboreLodgesJunaMahalRoute:
    DestinationsRanthamboreLodgesJunaMahalRoute,
  DestinationsRanthamboreLodgesIndexRoute:
    DestinationsRanthamboreLodgesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
