/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as LodgesRouteImport } from './routes/lodges'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations/index'
import { Route as DestinationsTadobaRouteImport } from './routes/destinations/tadoba'
import { Route as DestinationsRanthamboreRouteImport } from './routes/destinations/ranthambore'
import { Route as DestinationsKazirangaRouteImport } from './routes/destinations/kaziranga'
import { Route as DestinationsKanhaRouteImport } from './routes/destinations/kanha'
import { Route as DestinationsCorbettRouteImport } from './routes/destinations/corbett'
import { Route as DestinationsBandhavgarhRouteImport } from './routes/destinations/bandhavgarh'

const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const LodgesRoute = LodgesRouteImport.update({
  id: '/lodges',
  path: '/lodges',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsTadobaRoute = DestinationsTadobaRouteImport.update({
  id: '/destinations/tadoba',
  path: '/destinations/tadoba',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRanthamboreRoute = DestinationsRanthamboreRouteImport.update({
  id: '/destinations/ranthambore',
  path: '/destinations/ranthambore',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsKazirangaRoute = DestinationsKazirangaRouteImport.update({
  id: '/destinations/kaziranga',
  path: '/destinations/kaziranga',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsKanhaRoute = DestinationsKanhaRouteImport.update({
  id: '/destinations/kanha',
  path: '/destinations/kanha',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCorbettRoute = DestinationsCorbettRouteImport.update({
  id: '/destinations/corbett',
  path: '/destinations/corbett',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsBandhavgarhRoute = DestinationsBandhavgarhRouteImport.update({
  id: '/destinations/bandhavgarh',
  path: '/destinations/bandhavgarh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations/bandhavgarh': typeof DestinationsBandhavgarhRoute
  '/destinations/corbett': typeof DestinationsCorbettRoute
  '/destinations/kanha': typeof DestinationsKanhaRoute
  '/destinations/kaziranga': typeof DestinationsKazirangaRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/tadoba': typeof DestinationsTadobaRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations/bandhavgarh': typeof DestinationsBandhavgarhRoute
  '/destinations/corbett': typeof DestinationsCorbettRoute
  '/destinations/kanha': typeof DestinationsKanhaRoute
  '/destinations/kaziranga': typeof DestinationsKazirangaRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/tadoba': typeof DestinationsTadobaRoute
  '/destinations': typeof DestinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/conservation': typeof ConservationRoute
  '/itineraries': typeof ItinerariesRoute
  '/lodges': typeof LodgesRoute
  '/photography': typeof PhotographyRoute
  '/destinations/bandhavgarh': typeof DestinationsBandhavgarhRoute
  '/destinations/corbett': typeof DestinationsCorbettRoute
  '/destinations/kanha': typeof DestinationsKanhaRoute
  '/destinations/kaziranga': typeof DestinationsKazirangaRoute
  '/destinations/ranthambore': typeof DestinationsRanthamboreRoute
  '/destinations/tadoba': typeof DestinationsTadobaRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations/bandhavgarh'
    | '/destinations/corbett'
    | '/destinations/kanha'
    | '/destinations/kaziranga'
    | '/destinations/ranthambore'
    | '/destinations/tadoba'
    | '/destinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations/bandhavgarh'
    | '/destinations/corbett'
    | '/destinations/kanha'
    | '/destinations/kaziranga'
    | '/destinations/ranthambore'
    | '/destinations/tadoba'
    | '/destinations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/conservation'
    | '/itineraries'
    | '/lodges'
    | '/photography'
    | '/destinations/bandhavgarh'
    | '/destinations/corbett'
    | '/destinations/kanha'
    | '/destinations/kaziranga'
    | '/destinations/ranthambore'
    | '/destinations/tadoba'
    | '/destinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConservationRoute: typeof ConservationRoute
  ItinerariesRoute: typeof ItinerariesRoute
  LodgesRoute: typeof LodgesRoute
  PhotographyRoute: typeof PhotographyRoute
  DestinationsBandhavgarhRoute: typeof DestinationsBandhavgarhRoute
  DestinationsCorbettRoute: typeof DestinationsCorbettRoute
  DestinationsKanhaRoute: typeof DestinationsKanhaRoute
  DestinationsKazirangaRoute: typeof DestinationsKazirangaRoute
  DestinationsRanthamboreRoute: typeof DestinationsRanthamboreRoute
  DestinationsTadobaRoute: typeof DestinationsTadobaRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lodges': {
      id: '/lodges'
      path: '/lodges'
      fullPath: '/lodges'
      preLoaderRoute: typeof LodgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/tadoba': {
      id: '/destinations/tadoba'
      path: '/destinations/tadoba'
      fullPath: '/destinations/tadoba'
      preLoaderRoute: typeof DestinationsTadobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/ranthambore': {
      id: '/destinations/ranthambore'
      path: '/destinations/ranthambore'
      fullPath: '/destinations/ranthambore'
      preLoaderRoute: typeof DestinationsRanthamboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/kaziranga': {
      id: '/destinations/kaziranga'
      path: '/destinations/kaziranga'
      fullPath: '/destinations/kaziranga'
      preLoaderRoute: typeof DestinationsKazirangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/kanha': {
      id: '/destinations/kanha'
      path: '/destinations/kanha'
      fullPath: '/destinations/kanha'
      preLoaderRoute: typeof DestinationsKanhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/corbett': {
      id: '/destinations/corbett'
      path: '/destinations/corbett'
      fullPath: '/destinations/corbett'
      preLoaderRoute: typeof DestinationsCorbettRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/bandhavgarh': {
      id: '/destinations/bandhavgarh'
      path: '/destinations/bandhavgarh'
      fullPath: '/destinations/bandhavgarh'
      preLoaderRoute: typeof DestinationsBandhavgarhRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConservationRoute: ConservationRoute,
  ItinerariesRoute: ItinerariesRoute,
  LodgesRoute: LodgesRoute,
  PhotographyRoute: PhotographyRoute,
  DestinationsBandhavgarhRoute: DestinationsBandhavgarhRoute,
  DestinationsCorbettRoute: DestinationsCorbettRoute,
  DestinationsKanhaRoute: DestinationsKanhaRoute,
  DestinationsKazirangaRoute: DestinationsKazirangaRoute,
  DestinationsRanthamboreRoute: DestinationsRanthamboreRoute,
  DestinationsTadobaRoute: DestinationsTadobaRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
